import { Box, Flex, Text } from '@fluentui/react-northstar';
import { FC, KeyboardEventHandler, useEffect, useRef, useState } from 'react';
import { BaseCellProps, commonStyle, EditingState } from './common.ts';

export interface PeopleCellProps extends BaseCellProps<string[]> {
  suggestions?: string[];
}

/** GENERATED BY CLAUDE/GLM. NEED REFINEMENT. */
export const PeopleCell: FC<PeopleCellProps> = ({
  hovered,
  selected,
  onHover,
  onClick,
  onEdit,
  onCommit,
  onCancel,
  value = [],
  widthInPx,
  suggestions = []
}) => {
  const [state, setState] = useState<EditingState<string[]>>({ mode: 'read' });
  const [searchText, setSearchText] = useState('');
  const [showDropdown, setShowDropdown] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);

  const isEditing = selected && state.mode === 'edit';

  const filteredSuggestions = suggestions.filter((s) =>
    s.toLowerCase().includes(searchText.toLowerCase())
  );

  const handleClick = () => {
    if (selected) {
      setState({ mode: 'edit', draft: value });
      onEdit?.();
    } else {
      onClick?.();
    }
  };

  const handleHover = () => {
    onHover?.();
  };

  const handleKeyboardDiv: KeyboardEventHandler<HTMLDivElement> = (e) => {
    if (e.key === 'Enter') {
      setState({ mode: 'edit', draft: value });
      onEdit?.();
    } else if (e.key === 'Escape' && isEditing) {
      setState({ mode: 'read' });
      onCancel?.();
    }
  };

  const handleKeyboardInput: KeyboardEventHandler<HTMLInputElement> = (e) => {
    if (e.key === 'Enter' && searchText.trim()) {
      const newDraft = [...(state.mode === 'edit' ? state.draft : value)];
      if (!newDraft.includes(searchText.trim())) {
        newDraft.push(searchText.trim());
      }
      setState({ mode: 'edit', draft: newDraft });
      setSearchText('');
      inputRef.current?.focus();
    } else if (e.key === 'Escape') {
      setState({ mode: 'read' });
      onCancel?.();
    } else if (
      e.key === 'Backspace' && !searchText && state.mode === 'edit' &&
      state.draft.length > 0
    ) {
      // Remove last person when backspace is pressed on empty input
      const newDraft = [...state.draft];
      newDraft.pop();
      setState({ mode: 'edit', draft: newDraft });
    }
  };

  const handleBlur = async () => {
    if (!isEditing) {
      return;
    }

    const currentDraft = state.mode === 'edit' ? state.draft : value;
    if (JSON.stringify(currentDraft) !== JSON.stringify(value)) {
      await onCommit?.(currentDraft);
    }

    setState({ mode: 'read' });
    setShowDropdown(false);
  };

  const handleAddPerson = (person: string) => {
    const newDraft = [...(state.mode === 'edit' ? state.draft : value)];
    if (!newDraft.includes(person)) {
      newDraft.push(person);
    }
    setState({ mode: 'edit', draft: newDraft });
    setSearchText('');
    inputRef.current?.focus();
  };

  const handleRemovePerson = (person: string) => {
    if (state.mode === 'edit') {
      const newDraft = state.draft.filter((p) => p !== person);
      setState({ mode: 'edit', draft: newDraft });
    }
  };

  useEffect(() => {
    if (state.mode === 'edit') {
      inputRef.current?.focus();
    }
  }, [state.mode]);

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (
        dropdownRef.current &&
        !dropdownRef.current.contains(event.target as Node)
      ) {
        setShowDropdown(false);
      }
    };

    if (showDropdown) {
      document.addEventListener('mousedown', handleClickOutside);
    }

    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [showDropdown]);

  const currentPeople = state.mode === 'edit' ? state.draft : value;

  return isEditing
    ? (
      <Flex column style={{ width: widthInPx, flex: 'none' }} ref={dropdownRef}>
        <Flex
          vAlign='center'
          wrap
          gap='gap.smaller'
          style={{
            border: '1px solid #e0e0e0',
            padding: '4px 6px',
            minHeight: 32,
            boxSizing: 'border-box'
          }}
        >
          {currentPeople.map((person) => (
            <Flex
              key={person}
              vAlign='center'
              gap='gap.smaller'
              style={{
                border: '1px solid #e0e0e0',
                padding: '2px 8px',
                borderRadius: 12,
                background: '#f5f5f5'
              }}
            >
              <Text size='small'>{person}</Text>
              <Text
                size='small'
                style={{ cursor: 'pointer', color: '#666' }}
                onClick={(e) => {
                  e.stopPropagation();
                  handleRemovePerson(person);
                }}
              >
                ×
              </Text>
            </Flex>
          ))}
          <input
            ref={inputRef}
            value={searchText}
            onChange={(e) => setSearchText(e.target.value)}
            onKeyDown={handleKeyboardInput}
            onFocus={() => setShowDropdown(true)}
            onBlur={handleBlur}
            placeholder={currentPeople.length === 0 ? 'Add person...' : ''}
            style={{
              flex: 1,
              border: 'none',
              outline: 'none',
              minWidth: 60,
              padding: '2px',
              fontSize: 'inherit'
            }}
          />
        </Flex>
        {showDropdown && filteredSuggestions.length > 0 && (
          <Box
            style={{
              position: 'absolute',
              zIndex: 1000,
              marginTop: '4px',
              border: '1px solid #e0e0e0',
              background: 'white',
              maxHeight: 200,
              overflowY: 'auto',
              width: widthInPx
            }}
          >
            {filteredSuggestions.map((suggestion) => (
              <Box
                key={suggestion}
                onClick={(e) => {
                  e.stopPropagation();
                  handleAddPerson(suggestion);
                }}
                style={{
                  padding: '8px 12px',
                  cursor: 'pointer',
                  ':hover': { background: '#f5f5f5' }
                }}
              >
                <Text>{suggestion}</Text>
              </Box>
            ))}
          </Box>
        )}
      </Flex>
    )
    : (
      <div
        ref={inputRef}
        tabIndex={0}
        onClick={handleClick}
        onMouseOver={handleHover}
        onKeyDown={handleKeyboardDiv}
        className={commonStyle}
        data-hovered={!!hovered}
        data-selected={!!selected}
        style={{ width: widthInPx, flex: 'none', padding: '4px 6px' }}
      >
        {value.length > 0
          ? value.map((person) => (
            <span
              key={person}
              style={{
                border: '1px solid #e0e0e0',
                padding: '2px 8px',
                borderRadius: 12,
                background: '#f5f5f5',
                marginRight: '4px',
                display: 'inline-block'
              }}
            >
              {person}
            </span>
          ))
          : <span className='placeholder'>-</span>}
      </div>
    );
};
