/**
 * Given sets of winning projects, returning them updated with conflicts merged.
 *
 * For each item, `hasConflict = true` will be set if it does have conflicts.
 *
 * @param db the target db
 * @param projects winning docs of projects
 * @returns updated `projects` with fields merged accordingly. See `story.md`.
 */
export async function fetchConflictingProjectsAndShowMergedResult(
  db: PouchDB.Database,
  projects: Doc<Project>[]
) {
  const docs = await getLosingDocs(db, projects);

  // update in-place
  const dict = makeDict(projects, (proj) => proj._id);
  for (const d of docs) {
    const found = dict[d._id];
    if (found) {
      // different sprint_ids will be appended
      // different participant will be added
      // same participant with different roles will be appended
      found.hasConflict = true;

      // string list is merged in-place.
      mergeStringList(found.sprint_ids, d.sprint_ids);
      found.participants = mergeParticipants(found.participants, d.participants);
    }
  }

  return projects;
}

export async function fetchConflictingTasksAndShowMergedResult(
  db: PouchDB.Database,
  tasks: Doc<Task>[]
) {
  // console.log(tasks);
  const docs = await getLosingDocs(db, tasks);

  // update in-place
  const dict = makeDict(tasks, (task) => task._id);
  for (const d of docs) {
    const found = dict[d._id];
    if (found) {
      if (!Array.isArray(found.conflicts)) {
        found.conflicts = [];
      }

      found.conflicts.push(d);
    }
  }

  return tasks;
}

/**
 * Given an array, return an object with keys generated by fn and values the item itself.
 *
 * Good to be used to make an index to an array, so updates could accelerate.
 *
 * @param arr the array as input
 * @param fn how to get the key
 * @returns an object with `fn(item) -> item`
 */
export function makeDict<T>(
  arr: T[],
  fn: (item: T) => string
): Record<string, T> {
  const result: Record<string, T> = {};
  for (const item of arr) {
    const key = fn(item);
    result[key] = item;
  }

  return result;
}

async function getLosingDocs<T extends object>(
  db: PouchDB.Database,
  docs: Doc<T>[]
) {
  const ids: string[] = docs.map((d) => d._id);
  const conflicts = (await db.allDocs<Doc<T>>({
    include_docs: true,
    keys: ids,
    conflicts: true
  })).rows;

  const promises: Promise<Doc<T>>[] = [];
  for (const c of conflicts) {
    if ('doc' in c && c.doc) {
      const revs = c.doc._conflicts ?? [];
      const id = c.doc._id;
      revs.forEach((rev) => {
        promises.push(db.get(id, { rev }));
      });
    }
  }

  const batch = await Promise.all(promises);
  return batch;
}

/**
 * Merges unique items from `incoming` into `original` array in-place.
 * Items already present in `original` are not duplicated.
 *
 * @param original - The target array to merge into (modified in-place)
 * @param incoming - The source array to merge from
 */
function mergeStringList(original: string[], incoming: string[]) {
  const cache = new Set<string>(original);
  for (const item of incoming) {
    if (!cache.has(item)) {
      cache.add(item);
      original.push(item);
    }
  }
}

/**
 * Normalize participants to the current format.
 * Historical format: Record<string, string[]> (array of roles)
 * Current format: Record<string, { name: string; roles: Role[] }>
 */
function normalizeParticipants(
  participants: Project['participants'] | Record<string, string[]> | undefined
): Project['participants'] {
  if (!participants) return {};

  const result: Project['participants'] = {};
  for (const key in participants) {
    const value = participants[key];
    if (Array.isArray(value)) {
      // Historical format: array of roles
      result[key] = { name: key, roles: value as Role[] };
    } else {
      // Current format
      result[key] = value;
    }
  }
  return result;
}

function mergeParticipants(
  original: Project['participants'],
  incoming: Project['participants']
) {
  const normalizedOriginal = normalizeParticipants(original);
  const normalizedIncoming = normalizeParticipants(incoming);

  for (const key in normalizedIncoming) {
    if (key in normalizedOriginal) {
      // Keep original's name, merge roles
      mergeStringList(
        normalizedOriginal[key].roles,
        normalizedIncoming[key].roles
      );
    } else {
      normalizedOriginal[key] = { ...normalizedIncoming[key] };
    }
  }

  return normalizedOriginal;
}
